import sys
sys.path.append('../../common')  # noqa
import common
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib
matplotlib.style.use('ggplot')

if len(sys.argv) < 2:
    sys.exit('Please, input as arguments:\n' +
             '1. the generated pgm image name,\n' +
             '2. the full pgm image name,\n' +
             'Example usage:\n' +
             'python italy_draw_graph.py ' +
             'italy_100completed_3.pgm ' +
             'italy.pgm')
generated_name = sys.argv[1]
full_name = sys.argv[2]

# Load data from italy_100completed_3_a.pgm
# Data generated by k-nearest
data1 = np.loadtxt(generated_name, skiprows=3) # , delimiter=" ",usecols=499)

# Load data from italy.pgm - Chapter01/map_of_italy/italy.pgm
# Correct full data
data2 = np.loadtxt(full_name, skiprows=3) 

data2 = data2.reshape(692,500)

# Initialize a color array
colors = []

# Compare values and determine colors
for i in range(data1.shape[0]):
    for j in range(data1.shape[1]):
        if np.isnan(data1[i, j]) or np.isnan(data2[i, j]):
            colors.append('grey')
        elif data1[i, j] != data2[i, j]:
            colors.append('red')
        else:
            colors.append('green' if data1[i, j] == 1 else 'blue')

# Reshape colors array for plotting
colors = np.array(colors).reshape(data1.shape)

# Create a scatter plot
plt.scatter(*np.where(colors == 'red'), color='red', label='Different values')
plt.scatter(*np.where(colors == 'blue'), color='blue', label='Value = 0')
plt.scatter(*np.where(colors == 'green'), color='green', label='Value = 1')
plt.scatter(*np.where(colors == 'grey'), color='grey', label='NaN')

plt.xlabel('Column Index')
plt.ylabel('Row Index')
plt.title('Comparison of Data from italy_100completed_3_a.pgm and italy.pgm')
plt.legend()
plt.show()
